//
// Created by Liu, Zhiyan on 2019-05-23.
//

#ifndef NIGHTSWATCH_RANGER_OP_UPDATE_AGENT_CFG_H_
#define NIGHTSWATCH_RANGER_OP_UPDATE_AGENT_CFG_H_

#endif // NIGHTSWATCH_RANGER_OP_UPDATE_AGENT_CFG_H_
