//
// Created by Zhi Yan Liu on 2019-07-15.
//

#ifndef NIGHTSWATCH_RANGER_VERSION_H_
#define NIGHTSWATCH_RANGER_VERSION_H_

#define NIGHTSWATCH_RANGER_VER "0.1.3"

#endif // NIGHTSWATCH_RANGER_VERSION_H_
